add post on desktop
deltachat/deltachat-pages pull request #102
Opened 2018-10-02 23:47 UTC by ralphtheninja

2018-10-02 23:49 UTC, ralphtheninja commented
Forgot link to the forum.

2018-10-03 07:41 UTC, hpk42 requested changes
looks good, made a few comments regarding clarifications.  can help with finalizing tomorrow.

2018-10-03 07:41 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +We are working on a desktop application for Delta.Chat. It's written in electron, based on the [node bindings](https://github.com/deltachat/deltachat-node) and has a UI with strong similarities to Si
it's not just similartieis but partially based on the signal ui desktop code -- that should be clearly mentioned (without claiming it's "based" on laptop security wise or so)

2018-10-03 07:41 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +
doesn't Autocrypt setup  message (syncing between android and desktop) work? not sure if in both directions.

2018-10-03 07:41 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +
maybe also another section on how you can help? (css/design, windows support would be bigger items)

2018-10-03 07:41 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +If you have any feedback, please create an account at our [support forum](https://support.delta.chat/). From there we can create issues on respective github repository and take action from there.
maybe we can create a "desktop" category on the support site and mention it here? 
(don't have much online time today but tomorrow i could help)

2018-10-03 07:41 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +author: magnus
maybe do it as magnus and karissa?

2018-10-03 08:26 UTC, r10s commented
apart from the comments from hpk, this looks good to me :)
maybe add a small screenshot?

2018-10-03 09:41 UTC, ralphtheninja commented on _posts/2018-10-03-desktop-update.md
> +
Yes, it does. It's what I meant by 'import keys from another device'. Will rephrase.

2018-10-03 09:43 UTC, ralphtheninja commented on _posts/2018-10-03-desktop-update.md
> +If you have any feedback, please create an account at our [support forum](https://support.delta.chat/). From there we can create issues on respective github repository and take action from there.
Sure! Let me know when it's created. ping @lefherz

2018-10-03 10:08 UTC, ralphtheninja commented
> maybe add a small screenshot?

I'd love to add one, but it's quite a bit of work to get a good screenshot. Have one already? :)

2018-10-03 10:10 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +* [`AutoCrypt`](https://autocrypt.org/) setup message
"you can setup message" ? :) 
how about "sending and receiving [Autocrypt setup messages](https://autocrypt.org/level1.html#autocrypt-setup-message) for synchronizing secret keys between devices"

2018-10-03 10:12 UTC, hpk42 commented on _posts/2018-10-03-desktop-update.md
> +If you have any feedback, please create an account at our [support forum](https://support.delta.chat/). From there we can create issues on respective github repository and take action from there.
no blocker to add this -- quickly checked but the admin of discourse is quite extensive -- not sure where you can add it.  maybe @r10s knows. but we can do this after the post is out.

2018-10-03 10:12 UTC, hpk42 approved these changes
looks good -- i'd change the "autocrypt setup message" wording but otherwise it's fine.

2018-10-03 10:19 UTC, ralphtheninja commented
> looks good -- i'd change the "autocrypt setup message" wording but otherwise it's fine.

I just did. You want me to change it again? :)

2018-10-03 10:38 UTC, merged

2018-10-03 10:41 UTC, ralphtheninja commented
@r10s this feature:

![screenshot from 2018-10-03 12-40-53](https://user-images.githubusercontent.com/308049/46405779-9d26d100-c709-11e8-8036-e66e60f014b8.png)