Update help.md
deltachat/deltachat-pages pull request #131
Opened 2019-02-08 22:11 UTC by adbenitez

this seems to be wrong...

2019-02-08 23:16 UTC, r10s requested changes

2019-02-08 23:16 UTC, r10s commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
even if there is no padlock, the message is usually transport encrypted; the original sentence is correct therefore.

2019-02-08 23:21 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
but there are something wrong here, "eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-encryption" that is not an explanation of why it is transported encrypted, sounds like the original intention was to say that it is unencrypted because "eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-encryption"

2019-02-08 23:22 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
anyway if you say is ok, you are free to edit it :)

2019-02-08 23:22 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
or I can do it...

2019-02-08 23:25 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
anyway I think that if the idea is to say that it is encrypted it should say something like "eg. because your server uses SSL to encrypt the connection"

2019-02-08 23:27 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
but in the end, that is the standard, and this is not actually the mean of "secure" people expect, if the server uses SSL that doesn't mean the users at risk, etc. are save, I don't think it is fine to transmit a feeling of false security :-/

2019-02-08 23:29 UTC, adbenitez commented on en/help.md
> -- If there is **no padlock**, the message is usually transport encrypted eg. because you or the sender have disabled end-to-end-encryption or the sender uses an app that does not support end-to-end-e
in this context we are talking about e2e encryption and if there are no padlock  the messages is **not** e2e encrypted

2019-02-11 13:49 UTC, adbenitez commented
first time I do this, I hope clicking the "resolve conversation" button means I accept the change requested...

2019-02-11 13:51 UTC, adbenitez commented
anyway I still think there is something wrong with this statement... :P

2019-03-27 07:09 UTC, merged