add posts about desktop release v0.103.0
deltachat/deltachat-pages pull request #162
Opened 2019-05-22 20:07 UTC by Jikstra

2019-05-22 20:52 UTC, ralphtheninja approved these changes

2019-05-22 20:59 UTC, r10s commented
cool :)

@Jikstra technically: as the first paragraph is shown in the overview ([preview](https://deploy-preview-162--deltachat.netlify.com/en/blog)) it is better not to use an image there.

2019-05-22 21:09 UTC, r10s commented
@Jikstra did a pr with the changes i suggested: https://github.com/deltachat/deltachat-pages/pull/163

2019-05-22 21:27 UTC, nicodh commented
<img width="600" alt="location-streaming" src="https://user-images.githubusercontent.com/1428457/58210218-1bf86a80-7ce9-11e9-92a7-7f798763a87f.png">

2019-05-22 23:19 UTC, Jikstra commented
![picture v0 103 0](https://user-images.githubusercontent.com/34889164/58215151-c1670a80-7cf8-11e9-8e60-b6276e36992c.png)

2019-05-23 21:43 UTC, hpk42 commented
improved the blog post, as discussde with jikstra.  but integrating the screenshots is still missing. 

also to verify that no telemetry leackage happens to mapbox.com cc @nicodh

2019-06-07 14:10 UTC, Jikstra commented
I would propose to release 0.104.0 in the next days (currently only upgrading rpgp is blocking, that pr is currently in the ci pipeline) and update this post accordingly. This means including the new and awesome fixes/improvements in the changelog (a lot better performance for example :))

2019-06-26 13:19 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +**Import Notes about this release**:
Important

2019-06-26 13:19 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +  to an an already existing mobile version you need to synchronize your setups.
-an

2019-06-26 13:27 UTC, ralphtheninja requested changes

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +**Import Notes about this release**:
Important

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +  to an an already existing mobile version you need to synchronize your setups.
-an

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +  process could be nicer for existing Android/iOS Delta Chat users could be nicer ;)
two "could be nicer"

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +  There are now .deb archives for all major Ubuntu versions**
Unmatched `**`

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +- a lot of refactoring of the backand/state handling took place,
backend

2019-06-26 13:27 UTC, ralphtheninja commented on _posts/2019-06-25-desktop.md
> +- the desktop release now has support for simple markdown. Give it a try!
Maybe give some examples on how it works? I.e. using backticks etc.

2019-06-26 20:41 UTC, r10s commented
lgtm, nice work :)

2019-06-27 09:01 UTC, ralphtheninja approved these changes

2019-06-27 10:28 UTC, merged