Improve pages
deltachat/deltachat-pages pull request #194
Opened 2019-11-13 16:25 UTC by Simon-Laux

and add download page

2019-11-13 17:33 UTC, Simon-Laux commented
for easier reviewing https://github.com/deltachat/deltachat-pages/pull/194/files/7c67ba7752a73708aab58367ef03f083ffd7d005

2019-11-13 19:46 UTC, Jikstra commented on ca/download.md
> +Or just visit `https://get.delta.chat` on you're friends device.
typo: `your`

2019-11-14 00:37 UTC, r10s reviewed
i think the general layout should be a bit more "elegant" and should fit better to the overall layout. 
- eg. i would color the buttons in the color of the header, or chose a color that fits to that.
- also maybe just use lines instead of boxes
- the font size should match the rest of the page (we can also enlarge the font in the header)
- maybe the buttons should be of the same sizes

2019-11-14 11:11 UTC, ghost requested changes

2019-11-14 11:11 UTC, lefherz commented on assets/js/logic.js
> +function main() {
You could give assets/js/logic.js a more meaningful name, e.g. recommend.js - but maybe not important, as it is neither obvious what our other js file is doing. :woman_shrugging:

2019-11-14 11:11 UTC, lefherz commented on ca/download.md
> +[<img src="../assets/home/get-it-on-fdroid.png" alt="Get it on F-Droid" width="200" />](https://f-droid.org/app/com.b44t.messenger)
Why not just add the badges to the Android download box?

2019-11-14 11:11 UTC, lefherz commented on ca/download.md
> +Or just visit `https://get.delta.chat` on your friends device.
Do we really need a QR code on this page which links to it?

2019-11-14 11:11 UTC, lefherz commented on en/verify_downloads.md
> +  `{% include fingerprint-local %}`
Where do we get those variables from, where do we need to change them when we release something?

2019-11-14 11:12 UTC, lefherz commented
Thanks for your extensive work in refactoring this page! Overall great. So I mainly have some questions, and yeah, the Android buttons should be in the box I think.

2019-11-14 19:59 UTC, Simon-Laux commented on en/verify_downloads.md
> +  `{% include fingerprint-local %}`
there were there before, I just moved that part to another file. They are under the `_includes` folder

2019-11-14 20:03 UTC, Simon-Laux commented on ca/download.md
> +[<img src="../assets/home/get-it-on-fdroid.png" alt="Get it on F-Droid" width="200" />](https://f-droid.org/app/com.b44t.messenger)
Add or replace the other buttons? I was worried that it looks not too good if we mix mash the design, but I also don't want to remove them because maybe we'll find a solution for including them in the future.
Generally as with verify downloads section and Changelog I want to preserve the information that isn't in the new page otherwise. for the first time it doesn't have to be perfect.

2019-11-14 20:29 UTC, Simon-Laux commented on ca/download.md
> +Or just visit `https://get.delta.chat` on your friends device.
we advertised the testflight qr so I thought it would be useful.

2019-11-14 20:59 UTC, Simon-Laux commented
the translation system enables translators to break the whole site:
```
Liquid Exception: Liquid syntax error (line 208): Tag '{% включая standards-url %}' was not properly terminated with regexp: /\%\}/ in ru/help.md
```
```
- Смотрите [Стандарты, используемые в Delta Chat]({% включая standards-url %}).
```
the include code was translated too, which makes no sense cause it breaks the site

2019-11-14 21:12 UTC, lefherz commented on it/download.po
> +"<script src=\"../assets/js/logic.js\"></script>"
missed one here, I think ;) download-page.js

2019-11-14 21:12 UTC, lefherz commented on nb/download.po
> +"<script src=\"../assets/js/logic.js\"></script>"
Here too :)

2019-11-14 21:14 UTC, lefherz commented on uk/download.po
> +"<script src=\"../assets/js/logic.js\"></script>"
another one :)

2019-11-14 21:19 UTC, lefherz commented on ca/download.md
> +[<img src="../assets/home/get-it-on-fdroid.png" alt="Get it on F-Droid" width="200" />](https://f-droid.org/app/com.b44t.messenger)
I would replace them. We could make the APK button just a text link instead - it's meant for users who know what they do, after all.

But yeah, of course. Perfection is boring :P Preserving information is good :)

2019-11-14 21:23 UTC, Simon-Laux commented
> maybe the buttons should be of the same sizes

@r10s what do you mean by that? same width?

> we can also enlarge the font in the header

I'll try to do that, but we'll do another pr for more global site changes.

> also maybe just use lines instead of boxes

something like this?:
![2019-11-14_22-14](https://user-images.githubusercontent.com/18725968/68897237-5e957f80-072d-11ea-88e7-c8579c3175d1.png)

2019-11-14 21:33 UTC, Simon-Laux commented on uk/download.po
> +"<script src=\"../assets/js/logic.js\"></script>"
not too important that are po files

2019-11-14 21:47 UTC, Simon-Laux commented
maybe we should use http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/html2po.html for conversion instead of txt2po and use html. In future we would need our own converter that ignores html logic, jekyll liquid logic and markdown logic

2019-11-14 22:43 UTC, Simon-Laux commented
![2019-11-14_23-41](https://user-images.githubusercontent.com/18725968/68902417-8c33f600-0738-11ea-9562-9c21680e7a2e.png)
@lefherz now you have your badges inside

2019-11-15 00:34 UTC, ghost approved these changes

2019-11-15 00:38 UTC, lefherz commented
I like the look :) and I think it still looks good next to the other buttons.

Yeah, trademark rules suck. I think it's interesting how these buttons generate user trust; how many users would probably rather download from GPlay store than from our website. (Which is aligned with the Android settings, "untrusted sources" etc).

Not playing along would maybe be better than making us again dependent on stupid G**gle infrastructure. On the other hand it introduces a critical thinking-barrier for our users. Which might be a good thing. The more I think about it, the more undecided I am :D

2019-11-15 16:21 UTC, merged