Update download.md
deltachat/deltachat-pages pull request #230
Opened 2019-12-21 16:47 UTC by endbacher

re-order of menu points, link to provider database.

2020-01-02 14:46 UTC, ghost requested changes

2020-01-02 14:46 UTC, lefherz commented on en/download.md
> +# Changelogs
Thanks for the initiative! Can you quickly turn all headlines into h2?

2020-01-02 14:46 UTC, lefherz commented on en/download.md
> +* [FAQ multiclient](help#multiclient): How to synchronize Desktop with another Delta Chat app.
I suggest to move verify downloads to the bottom of these 3 points; while it is important for security, 99% of our users will want to know the other two things first.

2020-01-06 12:48 UTC, comradekingu commented on en/download.md
> +# Changelogs
Done

2020-01-06 12:49 UTC, comradekingu commented on en/download.md
> +* [FAQ multiclient](help#multiclient): How to synchronize Desktop with another Delta Chat app.
Done

2020-01-06 19:28 UTC, merged