Create 2020-09-13-belarus.md
deltachat/deltachat-pages pull request #374
Opened 2020-09-14 20:11 UTC by okdistribute

Open for changes/comments/updates, this is a first pass

2020-09-14 21:19 UTC, Simon-Laux commented
LGTM, besides the missing new thumbnail/cover image.

2020-09-19 10:00 UTC, missytake requested changes
With those small layouting changes, I'd say it's good to be published :) Or do any people want to work more on this?

2020-09-19 10:00 UTC, missytake commented on _posts/2020-09-13-belarus.md
> +
```suggestion
```

I would leave out this subheading - the title already generates a h1 heading saying "Belarus". Then the "it's critical that" paragraph will also appear on /blog as a preview, instead of "Belarus".

2020-09-19 10:00 UTC, missytake commented on _posts/2020-09-13-belarus.md
> +https://nitter.net/delta_chat/status/1293456217248079872
```suggestion
"Yes, @delta_chat works in Belarus, e.g. you can use it with Yandex (needs enabled IMAP support)"
-> [source: Twitter](https://nitter.net/delta_chat/status/1293454056661356546)

"yes, Delta Chat works in Belarusia even if Signal, Whatsapp etc. suffer blockings."
-> [source: Twitter](https://nitter.net/delta_chat/status/1293456217248079872)
```

Maybe it can look even nicer with some embedding or so...

2020-09-19 14:43 UTC, Simon-Laux commented on _posts/2020-09-13-belarus.md
> +https://nitter.net/delta_chat/status/1293456217248079872
maybe screenshot or somekind of styled qoute element, but I wouldn't start to embed iframes from third parties just to make it look cooler.

2020-09-19 22:13 UTC, r10s requested changes
lgtm. technically, however, the image in the header has to be replaced, as @Simon-Laux already pointed out.

2020-09-19 22:15 UTC, r10s commented
what would be a good image?

2020-09-20 19:34 UTC, okdistribute commented
good question @r10s -- perhaps an iconic photo of belarus resistance?

2020-09-22 09:33 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +It's critical that ordinary people can get information out of their country without the government knowing who they are or what they're talking about. This free communication forms the basis for poli
The basis of political freedom doesn't hinge on what a country even is. Nor does sending information out constitute diversity of opinion, but rather implicates freedom of communication.
Independent media is much less important than independent branches of government.

2020-09-22 09:35 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +From August 9 to August 12, Internet access in Belarus was severely restricted for a total of 61 hours, meaning only text messages and voice calls. Twitter and WhatsApp? broken. VPNs were blocked. Th
And radio? Twitter and WhatsApp are always broken. The Apple and Google stores are not the only ways of downloading apps. "you" is not likely to be in Belarus.

2020-09-22 09:36 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
"authoritarian" is a judgement call. The reader can make of what other information there is available, its own decisions. How many arrested, etc.?

2020-09-22 09:36 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +During the internet censorship in Belarus, we performed a variety of tests on Delta Chat. We found that some email services were still working, specifically Yandex and mail.ru
Who are "we"?

2020-09-22 09:37 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Delta Chat messages sent from Yandex looked like any other ordinary and boring email. This made Delta.Chat very difficult to block.
"appeared to", they look different.

2020-09-22 09:37 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +As far as we know from other researchers in the area, local email providers didn't forward the mail outside the country, but for a group of testers (~10-15 logs) of our own servers as well as yandex
```suggestion
As far as we know from other researchers in the area, local email providers didn't forward mail outside the country, but for a group of testers (~10-15 logs) of our own servers as well as Yandex and mail.ru, we were able to send email using STARTTLS.
```

2020-09-22 09:39 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Not only is it difficult to block, governments around the world actually don't really want to block email. Email is used for everything; from binine birthday cards, to finance, to life-saving informa
```suggestion
Not only is it difficult to block, governments around the world actually don't really want to block email, as it is used for everything; from benign birthday cards, to finance, to life-saving information. That means there is collateral damage when the government blocks its use. We've found that governments don't really do a great job of blocking decentralized protocols like email, even for even a short amount of time.
```

2020-09-22 09:42 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +This type of innovation is not going to just happen by itself in the private sector. Email is the shining star example of a decentralized protocol that works even when everything else doesn't, precis
What isn't going to happen? A lot came from the private sector already, including Delta Chat.
The backbone exchange is governmental, but not crucial, so not sure "dependency" is clear there.

2020-09-22 09:43 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Funding from the Open Technology Fund enabled our team at Delta Chat to dive even deeper into Email to produce a chat application that really works in places like Belarus.
```suggestion
Funding from the Open Technology Fund enabled our team at Delta Chat to dive even deeper into email to produce a chat application that really works in places like Belarus.
```

2020-09-22 09:45 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Delta Chat is open source software maintained by real people all over the world, who are funded through independent sources. It is THIS independence in particular that makes Delta Chat special. There
```suggestion
Delta Chat is libre software maintained by real people all over the world, who are funded through independent sources. It is THIS independence in particular that makes Delta Chat special. There's trust that it'll last beyond a particular political moment or a particular business model or economic cycle. In these scenarios, people are trusting their technology with their lives.
```
The OTF isn't independent. Could say it only takes money with no explicit political ties.

2020-09-22 09:45 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +In this moment, what we need are more decentralized protocols, like Email, and more independent applications, like delta.chat. We need more open standards built on research, not monopolies that are e
```suggestion
In this moment, what we need are more decentralized protocols, like email, and more independent applications, like delta.chat. We need more open standards built on research, not monopolies easily controlled by a single organization or government.
```

2020-09-22 09:46 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +"yes, Delta Chat works in Belarusia even if Signal, Whatsapp etc. suffer blockings."
```suggestion
"yes, Delta Chat works in Belarusia even if Signal, WhatsApp etc. are more broken than usual."
```

2020-09-22 09:46 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +-> [source: Twitter](https://nitter.net/delta_chat/status/1293456217248079872)
Need more independent applications on decentralized protocols you say?

2020-09-22 09:49 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
```suggestion
Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters, when it should be focused on bloggers.
```

2020-09-22 17:20 UTC, okdistribute commented on _posts/2020-09-13-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
I think this says that the authoritarian government of belarus should be focused on harassing bloggers?

2020-09-23 07:25 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
Shouldn't we all?

2020-09-23 07:29 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Twitter and WhatsApp? broken. VPNs were blocked.
```suggestion
Twitter and WhatsApp? Broken. VPNs were blocked.
```

2020-09-23 07:31 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +Messengers and services which were not prepared to circumvent censorship, including WhatsApp, Twitter and VPNs were blocked.
```suggestion
Messengers and services which were not prepared to circumvent censorship, including WhatsApp, Twitter and VPNs, all of which got blocked.
```

2020-09-23 07:33 UTC, comradekingu commented on _posts/2020-09-13-belarus.md
> +The government blocked Apple Store and Google Play, so even if you knew an app that worked for you, you still couldn't download it.
```suggestion
The government blocked the equally authoritarian Apple and Google Play stores, to the effect of preventing unsuspecting users from downloading even apps that worked.
```
Play a smarter game, win better prices.

2020-10-23 11:08 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +It's critical that ordinary people can get information out of their country without the government knowing who they are or what they're talking about. This free communication forms the basis for poli
This is called espionage where no meaningful distinction can be made, and the only thing critical about it is how DeltaChat shouldn't meddle in the interests of foreign governments or the makeup of them.
Communication to what is outside of the national state is not the bedrock of neither political freedom, nor does it constitute diversity of opinion. It seems like DeltaChat doesn't even understand how a national state operates.
In this case, that is particularly bad, because it is easy to use this against the likes of what DeltaChat the program does.

2020-10-23 11:09 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +meaning only text messages and voice calls.**
this is not an exclusive limitation.

2020-10-23 11:11 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Twitter and WhatsApp? broken. VPNs were blocked.
It is not the duty nor in the interest of DeltaChat to mention dragnet-ware. It is not in the interest of the point that could possibly be made either. They don't belong in the same sentence as VPNs, more than VPN could be replaced with any dragnet-VPN.

2020-10-23 11:14 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +The government blocked Apple Store and Google Play, so even if you knew an app that worked for you, you still couldn't download it.
This states dragnet stores are the only means of getting software for mobile devices. For an app that distributes outside of those means, I would think for reasons F-Droid isn't in that league, that is puzzling. This is a damaging sentiment.
F-Droid works just fine for this particular scenario. In the very least pay them the service of mentioning that for using their service.

2020-10-23 11:15 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Messengers and services which were not prepared to circumvent censorship were blocked.
relying on central authority and systems. Preparedness isn't arbitrary to this point.

2020-10-23 11:16 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +And you couldn't even install working ones such as Psiphon VPN if you were not preparing in advance,
double-negative

2020-10-23 11:23 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +because Apple Store and Google Play were blocked.
Anyone can compile Psiphon at any time. Anyone can spread it freely. These are significant distinctions of libre software, but instead. again, the Apple Store and Google Play are heralded as the only sources of opportunity.
Don't know where to begin with this sentence.

2020-10-23 11:24 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
This is still a judgement call, and it is biased reporting for no good reason. There is ample opportunity of doing it right here.

2020-10-23 11:31 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +During the internet censorship in Belarus, we performed a variety of tests on Delta Chat. We found that some email services were still working, specifically Yandex and mail.ru
Internet with small i. Unreferenced "we". Repetition of "we". "were" is redundant. Those aren't mail services, and there is https://en.wikipedia.org/wiki/Mail.Ru very little seperation between them and the other dragnet services not mentioned in this context, but instead earlier.
That doesn't look like DeltaChat is prepared and others aren't, it looks like it is unable to distinguish itself in any other form, and even makes a distinction between dragnet services that isn't there.

2020-10-23 11:32 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Delta Chat messages sent from Yandex looked like any other ordinary and boring email. This made Delta.Chat very difficult to block.
No they don't, and it is dangerous to propose they do. It is very easy to block, but somewhat costly.

2020-10-23 11:33 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +As far as we know from other researchers in the area, local email providers didn't forward the mail outside the country, but for a group of testers (~10-15 logs) of our own servers as well as email p
E-mail providers generally don't send mail. Lots of repetition.

2020-10-23 11:35 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Not only is it difficult to block, governments around the world actually don't really want to block email, as it is used for everything; from benign birthday cards, to finance, to life-saving informa
Plaintext e-mail is easy to block. That governments don't want to block it isn't why DeltaChat works. "Great job" is misplaced.

2020-10-23 11:35 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +## Independence is crucial
This is not an independent way to write, otherwise I agree.

2020-10-23 11:41 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +This type of innovation is not going to just happen by itself in the private sector. Email is the shining star example of a decentralized protocol that works even when everything else doesn't, precis
Depending on what the out of context "this type of" refers to, or even by itself. for e-mail it is plainly wrong.
This is happily untrue, as a product of what e-mail is, and development of it, the network it is generally sent on, and the servers responsible for doing it.
As an aside. DeltaChat isn't public, and neither independent, as it depends on the US government for the bulk of its funds. E-mail relies heavily on one business model, which is dragnet surveillance, and at best hosting and government backbone funding.

2020-10-23 11:44 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Funding from the Open Technology Fund enabled our team at Delta Chat to dive even deeper into email to produce a chat application that really works in places like Belarus.
Why wouldn't it? This just relies on assumption and very little background info.
Writing stuff like this is _precisely_ what "places like Belarus" uses in their rhetoric.
If the Open Technology Fund was not equally biased, it wouldn't be in jeopardy now.
I reiterate, **there is no reason to be sloppy here, and it is counterproductive.**

2020-10-23 11:45 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +Delta Chat is open source software maintained by real people all over the world, who are funded through independent sources. It is THIS independence in particular that makes Delta Chat special. There
The OTF is not an independent source, they answer halfway to the US president, and the rest to the US government from what I remember, as being part of RFA.

2020-10-23 11:47 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +In this moment, what we need are more decentralized protocols, like email, and more independent applications, like delta.chat. We need more open standards built on research, not monopolies easily con
We have enough decentralized platforms, we need to use those, and avoid use of those that aren't. Agree with the second sentence. We need more articles written that reflect it.

2020-10-23 11:47 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +"Yes, @delta_chat works in Belarus, e.g. you can use it with Yandex (needs enabled IMAP support)"
If Yandex works anyway, this fails to make a point out of why one should use DeltaChat, and instead substitutes it for an advert of Yandex. I despair.

2020-10-23 11:49 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +"yes, Delta Chat works in Belarusia even if Signal, Whatsapp etc. suffer blockings."
That isn't how "WhatsApp" is written. Don't write "Twitter" if the link is for Nitter. A via is the least one could ask for.

2020-10-23 11:53 UTC, comradekingu commented on _posts/2020-09-27-belarus.md
> +-> [source: Twitter](https://nitter.net/delta_chat/status/1293456217248079872)
DeltaChat citing itself, via the Twitter network, two sentences below

> We need more open standards built on research, not monopolies easily controlled by a single organization or government.

is the height of hypocrisy.

2020-10-24 18:04 UTC, hpk42 commented
Allan, please tune it down -- while some of your suggestions are useful, it's hard to deal with the amount of commentary and somewhat harsh criticism on a single blog post. Thanks.

2020-10-24 18:37 UTC, okdistribute commented
What's blocking this from merge? A photo?

2021-02-07 03:55 UTC, jbar commented on _posts/2020-09-13-belarus.md
> +Meanwhile, the authoritarian government of Belarus continued to harass, abuse, detain, and arrest media, journalists, and protesters.
If you only lived a month in Belarus, you would have know that "authoritarian" is NOT a judgement call.

2021-04-28 11:55 UTC, r10s commented
i think, this pr is stale. we can reopen it as needed.

2021-04-28 11:55 UTC, closed without merging