privacy policy updated: blogpost + new privacy policy in english/german
deltachat/deltachat-pages pull request #482
Opened 2021-10-06 14:58 UTC by Yettte

closes #485 

- [x] add new privacy policy to website
- [x] crosslinking statements
- [x] write blog post about new privacy policy and fix image /screenshot
- [x] remove privacy policy from transifex

2021-10-23 12:45 UTC, Simon-Laux commented
would rather add privacy policy as markdown and if need be for a document format - pdf.

2021-10-26 15:58 UTC, missytake commented on tools/t-dance.sh
> +sfiles=(blog contribute download help imprint index references user-voices verify-downloads)
@r10s you have a better overview over the transifex mechanisms than me; the goal is that the privacy policies are not pushed to transifex, so the transifex community doesn't need to bother with the lawyer lingo.

Would this change be sufficient to accomplish this? Does it have unwanted side effects? What do you think?

2021-10-26 16:52 UTC, Yettte commented
cross link on German GDPR apps page doesn't work

2021-10-27 10:24 UTC, missytake commented on en/gdpr.md
> +## Summary
Here we need a link to the website GDPR policy, right?

2021-10-27 10:36 UTC, r10s commented on tools/t-dance.sh
> +sfiles=(blog contribute download help imprint index references user-voices verify-downloads)
seems to look right, however, be aware that the english source is not available in the other languages under urls as `it/gdpr` then - if that is desired, one have to adapt $things.

in general, this reverts https://github.com/deltachat/deltachat-pages/pull/123/files#diff-9563f7bd6875f5c8783f17d47797e2fe0be109fef2066fc5763bd04493cf437cR21 - that time, we came to the  conclusion that it is easier just to keep the gdpr on transifex - but it was also working before, yes.

2021-10-27 10:39 UTC, missytake commented on tools/t-dance.sh
> +sfiles=(blog contribute download help imprint index references user-voices verify-downloads)
ah, so I need to copy the english one to it/ fr/ etc. as well? Will do.

For legal reasons german and english should be fine anyway. :shrug: 

Thanks!

2021-10-27 11:29 UTC, missytake commented
> cross link on German GDPR apps page doesn't work

fixed :)

2021-10-28 09:18 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +title: We updated our GDPR for our apps and website!
that's a little boring title.  Here is a suggestion 
```suggestion
title: New data protection officer appointed and refined privacy policies
```

2021-10-28 10:34 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +
this is a pretty boring beginning and sounds like excuses are coming ("we are all guilty, we have data" :)

2021-10-28 10:36 UTC, hpk42 commented on ca/gdpr-website.md
> +We have appointed a data protection officer: **Prof. Dr. Fabian Schmieder**, lexICT UG (limited), Ostfeldstr. 49, 30559 Hannover. You can contact him at info@lexict.de Keyword: DeltaChat.
This could contain a link to the "Meldebescheinigung".

2021-10-28 10:39 UTC, hpk42 requested changes
The news really is Fabian here, and we should first talk about that and who he is and that he has been helping us for a while already etc. This should contain some biographic details and point to his web page. Also a photo of him should be both on the blogpost-list and with the article itself.  It's fine to link to the meldebescheinigung on the side somewhere. Especially as a thumbnail it is not very beautiful. 

for the second news (refined privacy policies) i suggest something like this: 

Jointly we worked with Kai Korte from [LexICT](https://lexict.de) to professionalize and refine our privacy policy. We split the privacy policy into one for the apps, and another separate one for the optional use of the web site and community services. As the Russian surveillance authority Roskomnadzor [learned last year](https://twitter.com/delta_chat/status/1256137319150751744) our apps are e-mail apps and do not contact servers other than user-chosen e-mail providers. But if you choose to interact with our website, [support forum](https://support.delta.chat), payment or social media presences, you can read up on our  [web privacy policy](web-GDPR) for details. TLDR; no cookies, no tracking, no ads. You are welcome :)

2021-10-28 11:32 UTC, hpk42 commented on ca/gdpr.md
> +<b>End-to-end encryption</b>, if feasible by implementing <a href="https://autocrypt.org">Autocrypt</a>. User-friendly end-to-end encryption means that the requirements of the GDPR are already implem
```suggestion
<b>End-to-end encryption</b>, by implementing <a href="https://autocrypt.org">Autocrypt</a> and <a href="https://countermitm.readthedocs.io/en/latest/new.html">Verified groups</a>. User-friendly end-to-end encryption means that the requirements of the GDPR are already implemented at the technical level, <b>Privacy by Design</b>.
```

I think it's important to mention Verified groups here to preempt typical autocrypt-criticisms.  We regularly provide this Verified Group link in various channels and  the FAQ and should also lilnk it here.

2021-10-28 14:01 UTC, missytake commented on _posts/2021-10-06-blog-GDPR.md
> +
Did the privacy of Delta users get worse since the last update to the privacy policy? The only thing we do differently know is the iOS heartbeat, right? It would be nice if we could link to that, but we never blogged about it.

2021-10-29 11:54 UTC, hpk42 commented on ca/gdpr.md
> +<b>End-to-end encryption</b>, if feasible by implementing <a href="https://autocrypt.org">Autocrypt</a>. User-friendly end-to-end encryption means that the requirements of the GDPR are already implem
Why did you not accept the suggested change?

2021-10-29 12:44 UTC, Yettte commented on _posts/2021-10-06-blog-GDPR.md
> +
The idea for now is to wait until @r10s releases the new iOS features and then publish a post about how apple works much better now with Delta Chat mentioning the new features and the push notification fix since it was a problem that resulted in apple people not wanting to use Delta Chat.

2021-10-29 18:48 UTC, r10s commented on _posts/2021-10-06-blog-GDPR.md
> +
> The idea for now is to wait until @r10s releases the new iOS features

not sure i understand the idea - the heartbeat-feature is long released (since 2021-03, v1.17 :) 

there was sidenote at https://delta.chat/en/2021-02-04-ios-is-catching-up#what-else, all in all, notifications are more reliable than before, ppl report in that direction, however, apple may still throttle notifications, so we can still not give guarantees.

technically, we send a "deviceToken" provided by Apple to our server. our server pings Apple with that deviceToken every 20 minutes then. Apple may or may not wake up the Delta Chat app then. We do not attach anything to the deviceToken.

2021-10-31 01:18 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +It has been a while since the last update on Delta Chat privacy policy and some things have changed. We appointed Prof.Dr. Fabian Schmieder of [University of Applied Sciences and Arts Hanover](https:
```suggestion
A while has passed since the last Delta Chat privacy-policy update, and some things have changed. Prof.Dr. Fabian Schmieder of [University of Applied Sciences and Arts Hanover](https://im.f3.hs-hannover.de/en_us/studium/personen/prof-dr-fabian-schmieder/) has been appointed our data protection officer (DPO). He has been a helping a helping hand for a long time and is not only a great advisor, but also a brilliant pianist!:)
```

2021-10-31 01:19 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +Jointly we worked with Kai Korte from [LexICT](https://lexict.de) to professionalize and refine our privacy policy. We split the privacy policy into one for the [apps](gdpr), and another separate one
```suggestion
In conjunction with Kai Korte of [LexICT](https://lexict.de) the privacy policy has been further refined. It is split between the [apps](gdpr), and another for the optional use of the [website](gdpr-website) and community services.
```

2021-10-31 01:23 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +As the Russian surveillance authority Roskomnadzor [learned last year](https://twitter.com/delta_chat/status/1256137319150751744) our apps are e-mail apps and do not contact servers other than user-c
```suggestion
As an authority on oversight, the Russian surveillance authority Roskomnadzor least year learnt [our app is an e-mail client last year year](https://twitter.com/delta_chat/status/1256137319150751744), meaning it does not contact servers other than providers of e-mail services chosen by the user. In similar fashion, no cookies, tracking or ads are employed when interacting our website, [support forum](https://support.delta.chat), payment, or social media presences.
```

2021-10-31 01:25 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +If you have any questions or comments please file issues on github
```suggestion
Questions and comments can be forwarded as issues on [GitHub](https://github.com/deltachat/deltachat-pages/issues)
```

2021-10-31 01:26 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +or send a message to delta-privacy@merlinux.eu
```suggestion
or sending an Autocrypted message to delta-privacy@merlinux.eu 
```

2021-10-31 01:29 UTC, comradekingu commented on _posts/2021-10-06-blog-GDPR.md
> +
Does the iOS heartbeet "feature" run afoul of the "in similar fashion" statement below?

2021-11-01 14:00 UTC, Yettte commented on _posts/2021-10-06-blog-GDPR.md
> +
> > The idea for now is to wait until @r10s releases the new iOS features
> 
> not sure i understand the idea - the heartbeat-feature is long released (since 2021-03, v1.17 :)
> 
> there was sidenote at https://delta.chat/en/2021-02-04-ios-is-catching-up#what-else, all in all, notifications are more reliable than before, ppl report in that direction, however, apple may still throttle notifications, so we can still not give guarantees.
> 
> technically, we send a "deviceToken" provided by Apple to our server. our server pings Apple with that deviceToken every 20 minutes then. Apple may or may not wake up the Delta Chat app then. We do not attach anything to the deviceToken.

@hpk42 said that you'll soon release new apple features and we just thought that the heartbeat feature was not mentioned by itself in a blog, so we thought about mentioning it again once you release the new apple features and write a blog post about it anyway.

2021-11-04 13:59 UTC, Yettte commented on _posts/2021-10-06-blog-GDPR.md
> +
closes #482 
The final step to do is to manually copy the updated privacy policies in English to all the other languages again since there were changes in between. And check if the German version is the up to date one. 
@missytake or @Simon-Laux: maybe one of you could do this because then we are all set for publishing our policies and the blog! That would be great! Thanks a lot :)

2021-11-09 12:39 UTC, Yettte commented on _posts/2021-10-06-blog-GDPR.md
> +As the Russian surveillance authority Roskomnadzor [learned last year](https://twitter.com/delta_chat/status/1256137319150751744) our apps are e-mail apps and do not contact servers other than user-c
I do not quite understand your suggestion concerning Roskomnadzor and think that the other suggestions could interfere with DCs general posting style. Thanks anyway!

2021-11-09 15:43 UTC, comradekingu commented on ca/gdpr-website.md
> +The following information also serves to provide you with information about this and how we protect your personal data from manipulation, loss, destruction or misuse.
```suggestion
The following also serves to provide you with information about this and how we protect your personal data from manipulation, loss, destruction or misuse.
```

2021-11-10 09:49 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +It has been a while since the last update on Delta Chat privacy policy and some things have changed. We appointed Prof.Dr. Fabian Schmieder, professor for data protection and media law of the [Univer
```suggestion
It has been a while since the last update on Delta Chat privacy policy and some things have changed. We appointed Prof. Dr. Fabian Schmieder, professor for data protection and media law of the [University of Applied Sciences and Arts Hanover](https://im.f3.hs-hannover.de/en_us/studium/personen/prof-dr-fabian-schmieder/) and coauthor of the standard work [Betrieblicher Datenschutz (Operational data protection)](https://www.beck-shop.de/forgo-helfrich-schneider-betrieblicher-datenschutz/product/24093138), who is now our data protection officer. He has been helping us for a long time and is not only a great advisor but also a brilliant pianist!:)
```

2021-11-10 10:06 UTC, hpk42 requested changes
i made some small typo/phrase suggestions.  
additionally i think: 
- the file name should be changed to today's date
- the picture is too corporate, would be great to get a more casual one

otherwise we are approaching merge! :)

2021-11-10 10:06 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +Jointly we worked with Kai Korte from [LexICT](https://lexict.de) to professionalize and refine our privacy policy. We split the privacy policy into one for the [apps](gdpr), and another separate one
```suggestion
Jointly we worked with his colleague Kai Korte from [LexICT](https://lexict.de) to professionalize and refine our privacy policy. We split the privacy policy into one for the [apps](gdpr), and another separate one for the optional use of the [website](gdpr-website) and community services.
```

2021-11-10 10:06 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +[Last year](https://twitter.com/delta_chat/status/1256137319150751744) the Russian surveillance authority Roskomnadzor learned that our apps are e-mail apps and do not contact servers other than user
```suggestion
[Last year](https://twitter.com/delta_chat/status/1256137319150751744) the Russian surveillance authority Roskomnadzor learned that our apps are e-mail apps and do not contact servers other than user-chosen e-mail providers. If you optionally make use of our website, [support forum](https://support.delta.chat), payment or social media presences, you can now read up on our web privacy policy for details. TLDR; no cookies, no tracking, no ads. You are welcome :)
```

2021-11-10 10:06 UTC, hpk42 commented on _posts/2021-10-06-blog-GDPR.md
> +If you have any questions or comments please file issues on github
```suggestion
If you have any questions or comments please [file issues on Github](https://github.com/deltachat/deltachat-pages/issues/new/choose)
```

2021-11-10 10:46 UTC, missytake commented
Unless we ask him, I don't think we get more casual photos^^

![Screenshot_2021-11-10_11-43-05](https://user-images.githubusercontent.com/57442838/141099197-282d3dee-25fa-4201-9a2a-1e4d84e1e3d2.png)

2021-11-10 10:46 UTC, missytake commented
So let's just merge if we want to publish it today?

2021-11-10 11:47 UTC, missytake commented
@Yettte found a better one :)

2021-11-10 12:03 UTC, missytake commented on ca/gdpr.md
> +lang: en
is this `lang` title item still used for anything? We took the pages out of translation... I'm not entirely sure if we need to change it to `ca` (or the other languages, respectively).

2021-11-10 13:32 UTC, hpk42 approved these changes
i added the picture inline and thinks it's ready. will merge in a second.

2021-11-10 13:50 UTC, comradekingu commented
@missytake 
It isn't much harder to do it right the first time with all the suggestions.
Having it look professional is a big deal to those that consider adopting it in organizations, which is typically the kind of scenario where any of this gets read.

2021-11-10 16:54 UTC, missytake approved these changes

2021-11-10 16:55 UTC, merged