started linkifying legal references
deltachat/deltachat-pages pull request #495
Opened 2021-11-11 17:55 UTC by Yettte

2021-11-11 17:57 UTC, Yettte commented on de/gdpr-website.md
> +gemäß [Art.17 DSGVO](https://dsgvo-gesetz.de/art-17-dsgvo/) die Löschung deiner bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die Verarbeitung zur Ausübung des Rechts auf f
Tried to linkiyfy legal references but had problems with part three (html) format, different from markdown, still needs to be fixed.

2021-11-11 21:12 UTC, r10s commented on de/gdpr-website.md
> +Wir verwenden Dienste der Association Liberapay, Chez M. Coste, Le Bourg, St Jean Le Blanc 14770 Terres de Druance, Frankreich, verteten durch Charly Coste. Der Dienst ermöglicht Spendenzahlungen an
```suggestion
Wir verwenden Dienste der Association Liberapay, Chez M. Coste, Le Bourg, St Jean Le Blanc 14770 Terres de Druance, Frankreich, verteten durch Charly Coste. Der Dienst ermöglicht Spendenzahlungen an uns. Dazu erhebt Liberapay Daten wie die E-Mail-Adresse, Namen und ggfs. Kontodaten zur Zahlungsabwicklung. Wir selbst haben keinen Zugriff auf diese Daten. Die Datenschutzerklärung von Liberapay, abrufbar [hier](https://liberapay.com/about/privacy).
```

2021-11-11 21:16 UTC, r10s commented on de/gdpr-website.md
> +gemäß [Art.17 DSGVO](https://dsgvo-gesetz.de/art-17-dsgvo/) die Löschung deiner bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die Verarbeitung zur Ausübung des Rechts auf f
in HTML, Markdown-links just do not work.

instead of eg. `[Art.6 lit.a DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/)`  
you have to write `<a href="https://dsgvo-gesetz.de/art-6-dsgvo/">Art.6 lit.a DSGVO</a>`.

more common, Markdown is `[TEXT](LINK)` while HTML is `<a href="LINK">TEXT</a>` :)

2021-11-12 13:39 UTC, Simon-Laux commented on de/gdpr-website.md
> +1. du deine nach [Art.6 lit.a DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/) ausdrückliche Einwilligung dazu erteilt hast,
this change changes the list to be numbered, not lettered anymore. I don't know if it needs to be lettered for some reason? or does it not matter?

2021-11-12 14:08 UTC, Yettte commented on de/gdpr-website.md
> +gemäß [Art.17 DSGVO](https://dsgvo-gesetz.de/art-17-dsgvo/) die Löschung deiner bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die Verarbeitung zur Ausübung des Rechts auf f
Thanks Björn! I discussed with Nami and Holger and we decided to take out html from these sections, so it's fixed now :)

2021-11-12 14:09 UTC, Yettte commented on de/gdpr-website.md
> +1. du deine nach [Art.6 lit.a DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/) ausdrückliche Einwilligung dazu erteilt hast,
With Nami we figured it's not important because there are no references to letters in other parts of the text. But thanks for pointing this out!

2021-11-12 14:09 UTC, Yettte commented on de/gdpr-website.md
> +Wir verwenden Dienste der Association Liberapay, Chez M. Coste, Le Bourg, St Jean Le Blanc 14770 Terres de Druance, Frankreich, verteten durch Charly Coste. Der Dienst ermöglicht Spendenzahlungen an
also fixed :)

2021-11-12 14:11 UTC, Yettte commented
if @missytake, @r10s and @Simon-Laux could review again, I'd be happy. if everything is ok now I would copy paste the english GDPR in the other languages. thanks for review!

2021-11-12 14:41 UTC, r10s commented
as i am not deep into that, i leave final review to @missytake and @Simon-Laux

2021-11-12 18:02 UTC, missytake requested changes
Some small things :) maybe take another look at https://staging.delta.chat/495/en/, to see if everything looks correct.

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +Es muss <b>keine Datenschutz-Folgenabschätzung</b> für Delta Chat <a href="https://dsgvo-gesetz.de/art-35-dsgvo/">Art.35 DSGVO</a> durchgeführt werden, da keine Daten über die Nutzung als E-Mail App
```suggestion
Es muss <b>keine Datenschutz-Folgenabschätzung</b> für Delta Chat (<a href="https://dsgvo-gesetz.de/art-35-dsgvo/">Art.35 DSGVO</a>) durchgeführt werden, da keine Daten über die Nutzung als E-Mail App hinaus verarbeitet werden. Das Risiko für Rechte und Freiheiten natürlicher Personen beschränkt sich auf die unternehmensinterne Datenverarbeitung der E-Mail-Kommunikation und die der E-Mail-Anbieter.
```

Here used to be brackets ;)

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +Der Datenschutzbeauftragte der merlinux GmbH ist **Prof. Dr. Fabian Schmieder**, c/o lexICT UG (haftungsbeschränkt), Ostfelstraße 49, 30559 Hannover. Du kannst ihn über [info@lexict.de](mailto:info@l
```suggestion
Der Datenschutzbeauftragte der merlinux GmbH ist **Prof. Dr. Fabian Schmieder**, c/o lexICT UG (haftungsbeschränkt), Ostfelstraße 49, 30559 Hannover. Du kannst ihn über [info@lexict.de](mailto:info@lexict.de) mit Stichwort: DeltaChat kontaktieren.
```

The "kontaktieren" got lost here.

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +Rechtsgrundlage der Verarbeitung ist [Art.6 lit.b DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/), da du mit uns durch die Benutzung unserer Services einen Nutzungsvertrag hast.
```suggestion
Rechtsgrundlage der Verarbeitung ist [Art.6 Abs. 1 S. 1 lit.b DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/), da du mit uns durch die Benutzung unserer Services einen Nutzungsvertrag hast.
```

Ich think something got lost here during linking.

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +- Push Notification Provider für Android Systeme ist Google Firebase. Der Anbieter ist Google Inc. und weitere Informationen findest du unter [https://firebase.google.com/products/cloud-messaging/](h
This paragraph is removed by #497 anyway... doesn't really matter.

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
>      • Einstellungen
```suggestion
- Chatverläufe (Textnachrichten, Sprachnachrichten, Medien, …)
- Kontakte
- Einstellungen 
```

imho, if we want an unordered list in this place, we should do it with the markdown `- ` list, instead of `•` unicode bullet points^^

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +```
```suggestion

```

This would also mean that the \``` tags are not necessary - this is not a code block.

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +7. gemäß [Art.77 DSGVO](https://dsgvo-gesetz.de/art-77-dsgvo/) dich bei einer Aufsichtsbehörde zu beschweren. In der Regel kannst du dich hierfür an die Aufsichtsbehörde deines üblichen Aufenthaltsor
```suggestion
1. gemäß [Art.15 DSGVO](https://dsgvo-gesetz.de/art-15-dsgvo/) Auskunft über deine von uns verarbeiteten personenbezogenen Daten zu verlangen. Insbesondere kannst du Auskunft über die Verarbeitungszwecke, die Kategorie der personenbezogenen Daten, die Kategorien von Empfänger\*innen, gegenüber denen deine Daten offengelegt wurden oder werden, die geplante Speicherdauer, das Bestehen eines Rechts auf Berichtigung, Löschung, Einschränkung der Verarbeitung oder Widerspruch, das Bestehen eines Beschwerderechts, die Herkunft deiner Daten, sofern diese nicht bei uns erhoben wurden, sowie über das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling und ggf. aussagekräftigen Informationen zu deren Einzelheiten verlangen;
2. gemäß [Art.16 DSGVO](https://dsgvo-gesetz.de/art-16-dsgvo/) unverzüglich die Berichtigung unrichtiger oder Vervollständigung deiner bei uns gespeicherten personenbezogenen Daten zu verlangen;
3. gemäß [Art.17 DSGVO](https://dsgvo-gesetz.de/art-17-dsgvo/) die Löschung deiner bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die Verarbeitung zur Ausübung des Rechts auf freie Meinungsäußerung und Information, zur Erfüllung einer rechtlichen Verpflichtung, aus Gründen des öffentlichen Interesses oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist;
4. gemäß [Art.18 DSGVO](https://dsgvo-gesetz.de/art-18-dsgvo/) die Einschränkung der Verarbeitung deiner personenbezogenen Daten zu verlangen, soweit die Richtigkeit der Daten von dir bestritten wird, die Verarbeitung unrechtmäßig ist, du aber deren Löschung ablehnst und wir die Daten nicht mehr benötigen, du jedoch diese zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigst oder du gemäß [Art.21 DSGVO](https://dsgvo-gesetz.de/art-21-dsgvo/) Widerspruch gegen die Verarbeitung eingelegt hast;
5. gemäß [Art.20 DSGVO](https://dsgvo-gesetz.de/art-20-dsgvo/) deine personenbezogenen Daten, die du uns bereitgestellt hast, in einem strukturierten, gängigen und maschinenlesebaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen;
6. gemäß [Art.7(3) DSGVO](https://dsgvo-gesetz.de/art-7-dsgvo/) deine einmal erteilte Einwilligung jederzeit gegenüber uns zu widerrufen. Dies hat zur Folge, dass wir die Datenverarbeitung, die auf dieser Einwilligung beruhte, für die Zukunft nicht mehr fortführen dürfen und
7. gemäß [Art.77 DSGVO](https://dsgvo-gesetz.de/art-77-dsgvo/) dich bei einer Aufsichtsbehörde zu beschweren. In der Regel kannst du dich hierfür an die Aufsichtsbehörde deines üblichen Aufenthaltsortes oder Arbeitsplatzes oder unseres Geschäftssitzes wenden. Die für unseren Geschäftssitz zuständige Aufsichtsbehörde ist der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg in 70173 Stuttgart.
```

The empty lines need to be removed here, otherwise it's not one ordered list, but 7, which are not counted together. It would probably still look okay, just the structure is a bit weird. :shrug:

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
>  Germany
```suggestion
merlinux GmbH  
Represented by the managing director Holger Krekel  
Reichsgrafen Str. 20  
79102 Freiburg  
Germany
```
If you remove the code block, which I agree with, you need to append `  ` at the end of each line, so there is a line break. Inside code blocks you don't need them, but if you don't have them, this looks like this:

merlinux GmbH Represented by the managing director Holger Krekel Reichsgrafen Str. 20 79102 Freiburg Germany

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
>  Germany
(With lists, you don't need them either. Each list item is a new line anyway.)

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
> +5. it is carried out by a service provider acting on our behalf and on our exclusive instructions, whom we have carefully selected [(Art.28(1) GDPR)](https://gdpr-info.eu/art-28-gdpr/) and with whom
```suggestion
1. you have given your explicit consent in accordance with [Art.6 (1) lit.a GDPR](https://gdpr-info.eu/art-6-gdpr/),
2. the disclosure is necessary for the establishment, exercise or defense of legal claims pursuant to [Art.6 (1) lit.b GDPR](https://gdpr-info.eu/art-6-gdpr/) and there is no reason to assume that you have an overriding interest worthy of protection in the non-disclosure of your data,
3. in the event that a legal obligation exists for the disclosure pursuant to [Art.6 (1) lit.c GDPR](https://gdpr-info.eu/art-6-gdpr/), as well as
4. it is legally permitted and necessary according to [Art.6 (1) lit.b GDPR](https://gdpr-info.eu/art-6-gdpr/) for the processing of contractual relationships with you
5. it is carried out by a service provider acting on our behalf and on our exclusive instructions, whom we have carefully selected [(Art.28 (1) GDPR)](https://gdpr-info.eu/art-28-gdpr/) and with whom we have concluded a corresponding data processing agreement [(Art.28 (3) GDPR)](https://gdpr-info.eu/art-28-gdpr/), which obligates our contractor to implement, in particular, appropriate security measures and grants us comprehensive control powers.
```

again, no empty lines between list items, and some numbers got lost.

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
> +In the registration process, we collect your username, password and e-mail address. When register at the platform, you will enter into a user agreement for the purpose of processing your profile data
```suggestion
In the registration process, we collect your username, password and e-mail address. When register at the platform, you will enter into a user agreement for the purpose of processing your profile data. [Art.6 (1) lit.b GDPR](https://gdpr-info.eu/art-6-gdpr/) serves as the legal basis for this. The registration and the resulting storage of data is necessary for the use of the platform. We cannot provide this service without this data. The data provided will be stored by us until you request anonymization or deletion of your user account.
```

2021-11-12 18:02 UTC, missytake commented on de/gdpr.md
> +Rechtsgrundlage der Verarbeitung ist [Art.6 lit.b DSGVO](https://dsgvo-gesetz.de/art-6-dsgvo/), da du mit uns durch die Benutzung unserer Services einen Nutzungsvertrag hast.
Actually, maybe take a look again at those - quite many of them got lost during the edits. It's quite easy to spot in https://github.com/deltachat/deltachat-pages/pull/495/files :)

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
>  Ireland
Again, if you remove the code block, you need to add `  ` at the end of each line where you want a line break ;)

2021-11-12 18:02 UTC, missytake commented on en/gdpr-website.md
> +7. complain to a supervisory authority in accordance with [Art.77 GDPR](https://gdpr-info.eu/art-77-gdpr/). You can therefore usually contact the supervisory authority of your usual place of residenc
no empty lines here ;)

2021-11-12 18:02 UTC, missytake commented on en/gdpr.md
> +- Push Notification Provider for iOS systems are the Apple Services. If push notifications are enabled, the Apple Push Notification Service (iOS version) is used to provide this feature. For more inf
Hm, the first link here is broken.

2021-11-12 18:02 UTC, missytake commented on en/gdpr.md
> +7. complain to a supervisory authority in accordance with [Art.77 GDPR](https://gdpr-info.eu/art-77-gdpr/) of the GDPR. As a rule, you can contact the supervisory authority of your usual place of res
The empty lines again ;)

2021-11-12 18:02 UTC, missytake commented on en/gdpr.md
> +You can access and print out the current data protection declaration at any time at [https://delta.chat/de/gdpr](https://delta.chat/de/gdpr).
```suggestion
You can access and print out the current data protection declaration at any time at [https://delta.chat/gdpr](https://delta.chat/gdpr).
```
We want to link here to /gdpr, not the german one - from there, users get redirected to their browser language. Otherwise, english visitors of the website have to try to understand german law terms ;) no experience I wish upon anyone

2021-11-15 11:42 UTC, Yettte commented on en/gdpr-website.md
>  Germany
thank you very much for all the tips and suggestions Nami! I think the code block was on the old page as well (assuming that you mean the grey background when you say code block) which is why I thought leaving it as it was before. Maybe something also went wrong, when I copy pasted from cryptpad code file (where I edited) into here? I'll double check :)

2021-11-15 11:54 UTC, Yettte commented on en/gdpr.md
> +- Push Notification Provider for iOS systems are the Apple Services. If push notifications are enabled, the Apple Push Notification Service (iOS version) is used to provide this feature. For more inf
when I put it in the search bar it works... Or do you meant that I linked it wrong?

2021-11-15 17:37 UTC, missytake commented on en/gdpr.md
> +- Push Notification Provider for iOS systems are the Apple Services. If push notifications are enabled, the Apple Push Notification Service (iOS version) is used to provide this feature. For more inf
https://support.apple.com/en-au/guide/deployment-reference-ios/ior9d28751c0/web gives me a 404 error^^

https://support.apple.com/guide/deployment-reference-ios/allowing-devices-to-work-with-apns-ior9d28751c0/web, the version before the PR, works for me.

2021-11-15 17:52 UTC, missytake commented on en/gdpr-website.md
> +You can contact YouTube's data protection officer under [https://support.google.com/policies/contact/general\_privacy\_form](https://support.google.com/policies/contact/general\_privacy\_form).
```suggestion
You can contact YouTube's data protection officer under [https://support.google.com/policies/contact/general\_privacy\_form](https://support.google.com/policies/contact/general_privacy_form).
```
Unfortunately, this link is broken now. Maybe this helps?

2021-11-15 17:52 UTC, missytake commented on en/gdpr.md
> +- Push Notification Provider for iOS systems are the Apple Services. If push notifications are enabled, the Apple Push Notification Service (iOS version) is used to provide this feature. For more inf
Nevermind, it works now :)

2021-11-15 17:54 UTC, missytake requested changes
One broken link left! Missed it the first time, apparently ;)

2021-11-16 14:26 UTC, Yettte commented
Ok, I double checked all links, everything works for me, @missytake, thank you very much for your help and review! Feel free to merge :)

2021-11-16 14:29 UTC, missytake commented
Great :) I also fixed it in german, that one also slipped through my eyes. So do we copy-paste the english version to the other languages in this PR or in a separate one?

2021-11-16 14:31 UTC, Yettte commented
> Great :) I also fixed it in german, that one also slipped through my eyes. So do we copy-paste the english version to the other languages in this PR or in a separate one?

omg, I missed that one as well, I don't get it, maybe I spent too much time with these documents :/ I can copy paste the english versions to the other languages if there is no trouble with transifex anymore.

2021-11-17 16:06 UTC, missytake approved these changes
nice, finally!

2021-11-17 16:06 UTC, merged