WIP: dapsi2blogpost
deltachat/deltachat-pages pull request #515
Opened 2022-01-14 18:31 UTC by Yettte

Blogpost for dapsi phase 2 wrap up. Screenshots of comparison table are still missing, review of text needed.

2022-01-14 20:32 UTC, missytake commented
Hm, right now the page isn't displayed - you need to delete the first (empty) line, and rename the file, so the `_` is a `-`

Apparently it doesn't work with _ in the filename :/

2022-01-17 11:44 UTC, Yettte commented
> Hm, right now the page isn't displayed - you need to delete the first (empty) line, and rename the file, so the `_` is a `-`
> 
> Apparently it doesn't work with _ in the filename :/

thanks nami! I changed the file name, should work now

2022-01-17 13:03 UTC, missytake commented
Cool :) the spaces in the links (between the `[]` and the `()`) have to go away, too, but some of the links aren't complete yet anyway, right?

2022-01-17 13:04 UTC, missytake commented on _posts/2022-01-16-dapsi2blogpost.md
> +The [DAPSI](https://dapsi.ngi.eu/hall-of-fame/eppd/) funding did not only result in an email provider comparison directory but also helped to improve Delta Chat's onboarding and usability! We release
```suggestion
The [DAPSI](https://dapsi.ngi.eu/hall-of-fame/eppd/) funding did not only result in an email provider comparison directory but also helped to improve Delta Chat's onboarding and usability! We released [quota and connectivity](https://delta.chat/en/2021-08-24-updates) and the [account switcher](https://delta.chat/en/2021-11-17-releases) which we are quite happy with.
```

like this :)

2022-01-17 13:05 UTC, Yettte commented
> Cool :) the spaces in the links (between the `[]` and the `()`) have to go away, too, but some of the links aren't complete yet anyway, right?

Exactly, I put them only as placeholders

2022-01-19 16:04 UTC, missytake requested changes
2 small things :)

2022-01-19 16:04 UTC, missytake commented on _posts/2022-01-16-dapsi2blogpost.md
> +    <b>Download</b>provider comparison table.
```suggestion
    <b>Download</b> provider comparison table.
```

one small typo :)

2022-01-19 16:04 UTC, missytake commented on _posts/2022-01-16-dapsi2blogpost.md
> +         width="260" style="border-width: 1px; border-color: grey; border-style: solid;"/><br>
```suggestion
         style="border-width: 1px; border-color: grey; border-style: solid;"/><br>
```

260 width is really small; if we leave it out, it looks quite good :)

2022-01-19 16:37 UTC, missytake approved these changes

2022-01-19 16:48 UTC, merged