WIP: added blogpost about how to setup mailcow + mailadm
deltachat/deltachat-pages pull request #604
Opened 2023-01-22 17:46 UTC by missytake

- [ ] use 1st person plural instead of singular

2023-01-23 11:40 UTC, brabo commented
looks nice!

2023-01-23 13:06 UTC, missytake commented on _posts/2023-01-23-mailadm-mailcow-setup-guide.md
> +```
Maybe we should just build mailadm-image.tar in the github.com/deltachat/mailadm CI on every tag or so and link to it here? We could do a new mailadm release soon anyway.

2023-01-23 13:11 UTC, missytake commented on _posts/2023-01-23-mailadm-mailcow-setup-guide.md
> +```
But let's do this later, this shouldn't block publishing this.

2023-01-23 13:45 UTC, brabo commented on _posts/2023-01-23-mailadm-mailcow-setup-guide.md
> +```
yeah, let's do that later. we can still improve on some points anyway.

2023-01-24 16:41 UTC, missytake commented
We discussed to put the guide on a dedicated page, and use the blogpost mainly to announce that and announce the upcoming workshops :)

2023-01-25 14:49 UTC, missytake commented
**README.md** says at "add new page":

> - run `./tools/t-dance push--do-this-only-from-master`

We need to do this after merging, I think, it errors out if you are not on master branch :shrug:

2023-01-26 17:57 UTC, link2xt commented on en/serverguide.md
> +### Adding Domain in Mailcow
Does this step somehow automatically generate the TLS certificate for the added domain? At which step Let's Encrypt (I assume) is used to get the certificate?

2023-01-27 08:32 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +IP reputation and configuration parameters like spam checking, rate limits, and
```suggestion
Chat. In short - most mail servers will work well, and reliability depends more on their
IP reputation and configuration parameters like spam checking, rate limits, and
```

2023-01-27 08:33 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +the easiest to manage is [Mailcow](https://mailcow.email).
```suggestion
attachment size how well it works with Delta Chat. 
One feature-complete mail-server we have successfully worked with successfully is  [Mailcow](https://mailcow.email).
```

2023-01-27 08:34 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +from you. This way, you can't do much damage with a misconfigured postfix; but
```suggestion
from you. This way, you can't easily end up with a misconfigured postfix; but
```

2023-01-27 09:59 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +for Delta Chat, the users just need to scan one QR code and are logged in.
```suggestion

We implemented an automated e-mail account management tool
to help admins give out accounts to users, 
both random short-lived ("burner") or longer-living accounts. 
[Mailadm](https://mailadm.readthedocs.io/) is implemented in Python 
and uses a minimal part of the [ReST HTTP API of mailcow](https://mailcow.docs.apiary.io/#).
Mailadm allows an admin group to create and hand out "tokens" (URLs with a secret number) 
to users who just need to scan one QR code and are logged in automatically.
```
let's not go overboard with praise here and not single out mailcow too much. Other solutions could also work nice, so let's just be descriptive here.

2023-01-27 10:02 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +and [send us your feedback](mailto:mailadm@testrun.org) about it!
```suggestion
With this blog post, we also publish  [a new guide](serverguide), which you can use to setup
a mailcow  server of your own, together with mailadm as easy account creation tool
to bring your friends and family to Delta Chat. 
We are happy about  [any feedback](mailto:mailadm@testrun.org) 
about our setup guidance and mailadm installation instructions!
```

2023-01-27 10:03 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +## Upcoming Workshops
```suggestion
## Upcoming mailcow/mailadm setup sessions in Amsterdam, Bruxelles, Montpellier and Gent
```

2023-01-27 10:05 UTC, hpk42 commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +title: New Guide for Setting up Mail Servers for Delta Chat - and Upcoming Workshops!
```suggestion
title: New Mail Server Setup Guide for Delta Chat - and Upcoming Workshops!
```

2023-01-27 10:07 UTC, hpk42 requested changes
generally fine with this but let's not advertise/single out mailcow too much.  It is one thing we use and have had success in using but i wouldn't go as far right now as to recommend it above everything else. After all anyone could implement a few HTTP-ReST API calls (maybe not in PHP :) and use mailadm.  You don't need to accept my precise suggestions but please address the general more careful "decentralized" attitude. Thanks!

2023-01-27 11:16 UTC, missytake commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +title: New Guide for Setting up Mail Servers for Delta Chat - and Upcoming Workshops!
hm, not a fan... verbs > substantives. "mail server setup guide" is technically more correct, but as a reader it's harder to wrap your mind around it. I'm a bit nitpicky about this, but headlines are important^^

2023-01-27 11:27 UTC, missytake commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +## Upcoming Workshops
I wrote something similar :)

2023-01-27 11:27 UTC, missytake commented on _posts/2023-01-26-upcoming-mail-server-workshops.md
> +and [send us your feedback](mailto:mailadm@testrun.org) about it!
I wrote something similar?

2023-01-27 11:39 UTC, missytake commented on en/serverguide.md
> +### Adding Domain in Mailcow
The TLS certificate is requested during this step: https://github.com/deltachat/deltachat-pages/blob/bbbcfc2f80b2f3215ad4e1cda1e9333197c2c2b0/en/serverguide.md?plain=1#L144

Every time the acme-mailcow container (re)starts, it requests new certificates, and https://docs.mailcow.email/post_installation/firststeps-ssl/#lets-encrypt-out-of-the-box also suggests to restart the mailcow-acme container to re-trigger the TLS certificate generation.

Which TLS certificates are requested by acme-mailcow does not depend on which domains are added in the web interface - even if example.org is added here, *actually* the mail server doesn't need a cert for `example.org`, only for, `autodiscover.example.org` and/or `autoconfig.example.org`, which then point to `mail.example.org` (for which a certificate is generated.

So which certs are requested depends on the `MAILCOW_HOSTNAME` and `ADDITIONAL_SAN` parameters - and I think some magic is used to also request certs for `autodiscover.example.org` and `autoconfig.example.org` even though `example.org` is never specified anywhere in the config. This I'm also a bit bewildered about.

2023-01-27 12:02 UTC, hpk42 commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +One feature-complete mail-server we have successfully worked with successfully is  [Mailcow](https://mailcow.email).
```suggestion
One feature-complete mail-server we have successfully worked with is  [Mailcow](https://mailcow.email).
```

2023-01-27 12:03 UTC, hpk42 commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +rspamd, wraps them into a present through docker, and ties a ribbon around it
```suggestion
rspamd, and wraps them in a docker-compose deployment. 
```

2023-01-27 12:04 UTC, hpk42 commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +about our [mail server and mailadm installation instructions](serverguide)!
not sure why the doubling here, but ok.

2023-01-27 12:04 UTC, hpk42 commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +- `2023-03-31` - `2023-04-02`: [Newline](https://hackerspace.gent/newline/2023/), Gent
does this list address off-pr remarks from @brabo ?

2023-01-27 12:07 UTC, missytake commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +about our [mail server and mailadm installation instructions](serverguide)!
So that the link to the guide is at the end of the paragraph :) and invites clicking on it ;)

2023-01-27 12:08 UTC, missytake commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +- `2023-03-31` - `2023-04-02`: [Newline](https://hackerspace.gent/newline/2023/), Gent
yep :)

2023-01-27 12:11 UTC, missytake commented on _posts/2023-01-27-upcoming-mail-server-workshops.md
> +rspamd, wraps them into a present through docker, and ties a ribbon around it
buuuut - the metaphor is so nice!

(and the . is too much in the end, as the next line starts lower case)

I mean, we stroke the rest of my personal writing style out of the post already, now that doesn't really fit in anymore I guess^^

2023-01-27 12:14 UTC, hpk42 approved these changes

2023-01-27 12:15 UTC, merged